apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  serviceName: "prometheus"
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
    spec:
      containers:
      - image: docker.io/prom/prometheus:v2.36.2
        name: prometheus
        volumeMounts:
        - name: prometheus-config
          mountPath: "/etc/prometheus/prometheus.yaml"
          subPath: "prometheus.yml"
        - name: data
          mountPath: "/prometheus" 
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: data
        persistentVolumeClaim:
           claimName: pvc
